* *********************************************************
* *
* * 05/03/00               DATA.DBC               04:27:27
* *
* *********************************************************
* *
* * Description:
* * This program was automatically generated by GENDBC
* * Version 2.26.67
* *
* *********************************************************
* *
* * << modified by an, 05/03/00 >>
* * 
* * PLEASE KEEP ALL DATA FILES IN LOCAL "DATA" DIRECTORY :-
* *
* * DATABASE: 
* *     data.dbc
* * LOCAL DBF:- 
* *     rpttab.dbf, usrpwd.dbf
* * CONNECTION:-
* *     rm_data ( POINT TO "abook" ODBC DSN - MUST MATCH TO DATABASE ON SERVER) 
* * REMOTE VIEW:-
* *     rv_city, rv_occupation, rv_company_type
* *     rv_tbctrl, rv_tbdata, rv_friend, rv_company
* *     rv_friend01, rv_friend02
* *
* * HOW TO CREATE DATABASE ON SERVER ?
* * PLEASE LOOK AT "SERVER" DIRECTORY, 
* * THERE ARE SOME ISQL-SCRIPT EXAPLES TO CREATE "ABOOK" DATABASE ON SERVER
* *     createdb_mssql.sql  : MS SQL SERVER
* *     createdb_sqlany.sql : SYBASE SQL ANYWHERE
* *     createdb_oracle.sql  : ORACLE
* * 
* *     G O O D L U C K !
* *
* *********************************************************

CLOSE DATA ALL
CREATE DATABASE 'DATA\DATA.DBC'

***** Table setup for RPTTAB *****
CREATE TABLE 'DATA\RPTTAB.DBF' NAME 'RPTTAB' ( ;
 CODE C(10) NOT NULL, ;
 NAME C(30) NOT NULL ;
)

***** Create each index for RPTTAB *****
ALTER TABLE 'RPTTAB' ADD PRIMARY KEY CODE TAG PKEY


***************** Connection Definitions RM_DATA ***************

CREATE CONNECTION RM_DATA ; 
   DATASOURCE "abook" ; 
   USERID "" ; 
   PASSWORD ""

=DBSetProp('RM_DATA', 'Connection', 'Asynchronous', .F.)
=DBSetProp('RM_DATA', 'Connection', 'BatchMode', .T.)
=DBSetProp('RM_DATA', 'Connection', 'Comment', '')
=DBSetProp('RM_DATA', 'Connection', 'DispLogin', 1)
=DBSetProp('RM_DATA', 'Connection', 'ConnectTimeOut', 15)
=DBSetProp('RM_DATA', 'Connection', 'DispWarnings', .F.)
=DBSetProp('RM_DATA', 'Connection', 'IdleTimeOut', 0)
=DBSetProp('RM_DATA', 'Connection', 'QueryTimeOut', 0)
=DBSetProp('RM_DATA', 'Connection', 'Transactions', 1)
=DBSetProp('RM_DATA', 'Connection', 'Database', '')

***************** View setup for RV_CITY ***************

CREATE SQL VIEW "RV_CITY" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT code, name FROM tbdata WHERE tabref = '01' ORDER BY name

DBSetProp('RV_CITY', 'View', 'UpdateType', 1)
DBSetProp('RV_CITY', 'View', 'WhereType', 3)
DBSetProp('RV_CITY', 'View', 'FetchMemo', .T.)
DBSetProp('RV_CITY', 'View', 'SendUpdates', .F.)
DBSetProp('RV_CITY', 'View', 'UseMemoSize', 255)
DBSetProp('RV_CITY', 'View', 'FetchSize', 100)
DBSetProp('RV_CITY', 'View', 'MaxRecords', -1)
DBSetProp('RV_CITY', 'View', 'Tables', 'tbdata')
DBSetProp('RV_CITY', 'View', 'Prepared', .F.)
DBSetProp('RV_CITY', 'View', 'CompareMemo', .T.)
DBSetProp('RV_CITY', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_CITY', 'View', 'FetchSize', 100)
DBSetProp('RV_CITY', 'View', 'Comment', "")
DBSetProp('RV_CITY', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_CITY', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_CITY
* Props for the RV_CITY.code field.
DBSetProp('RV_CITY.code', 'Field', 'KeyField', .T.)
DBSetProp('RV_CITY.code', 'Field', 'Updatable', .F.)
DBSetProp('RV_CITY.code', 'Field', 'UpdateName', 'tbdata.code')
DBSetProp('RV_CITY.code', 'Field', 'DataType', "C(2)")
* Props for the RV_CITY.name field.
DBSetProp('RV_CITY.name', 'Field', 'KeyField', .F.)
DBSetProp('RV_CITY.name', 'Field', 'Updatable', .T.)
DBSetProp('RV_CITY.name', 'Field', 'UpdateName', 'tbdata.name')
DBSetProp('RV_CITY.name', 'Field', 'DataType', "C(50)")

***************** View setup for RV_OCCUPATION ***************

CREATE SQL VIEW "RV_OCCUPATION" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT code, name FROM tbdata WHERE tabref = '02' ORDER BY name

DBSetProp('RV_OCCUPATION', 'View', 'UpdateType', 1)
DBSetProp('RV_OCCUPATION', 'View', 'WhereType', 3)
DBSetProp('RV_OCCUPATION', 'View', 'FetchMemo', .T.)
DBSetProp('RV_OCCUPATION', 'View', 'SendUpdates', .F.)
DBSetProp('RV_OCCUPATION', 'View', 'UseMemoSize', 255)
DBSetProp('RV_OCCUPATION', 'View', 'FetchSize', 100)
DBSetProp('RV_OCCUPATION', 'View', 'MaxRecords', -1)
DBSetProp('RV_OCCUPATION', 'View', 'Tables', 'tbdata')
DBSetProp('RV_OCCUPATION', 'View', 'Prepared', .F.)
DBSetProp('RV_OCCUPATION', 'View', 'CompareMemo', .T.)
DBSetProp('RV_OCCUPATION', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_OCCUPATION', 'View', 'FetchSize', 100)
DBSetProp('RV_OCCUPATION', 'View', 'Comment', "")
DBSetProp('RV_OCCUPATION', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_OCCUPATION', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_OCCUPATION
* Props for the RV_OCCUPATION.code field.
DBSetProp('RV_OCCUPATION.code', 'Field', 'KeyField', .T.)
DBSetProp('RV_OCCUPATION.code', 'Field', 'Updatable', .F.)
DBSetProp('RV_OCCUPATION.code', 'Field', 'UpdateName', 'tbdata.code')
DBSetProp('RV_OCCUPATION.code', 'Field', 'DataType', "C(2)")
* Props for the RV_OCCUPATION.name field.
DBSetProp('RV_OCCUPATION.name', 'Field', 'KeyField', .F.)
DBSetProp('RV_OCCUPATION.name', 'Field', 'Updatable', .T.)
DBSetProp('RV_OCCUPATION.name', 'Field', 'UpdateName', 'tbdata.name')
DBSetProp('RV_OCCUPATION.name', 'Field', 'DataType', "C(50)")

***************** View setup for RV_COMPANY_TYPE ***************

CREATE SQL VIEW "RV_COMPANY_TYPE" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT code, name FROM tbdata WHERE tabref = '03' ORDER BY name

DBSetProp('RV_COMPANY_TYPE', 'View', 'UpdateType', 1)
DBSetProp('RV_COMPANY_TYPE', 'View', 'WhereType', 3)
DBSetProp('RV_COMPANY_TYPE', 'View', 'FetchMemo', .T.)
DBSetProp('RV_COMPANY_TYPE', 'View', 'SendUpdates', .F.)
DBSetProp('RV_COMPANY_TYPE', 'View', 'UseMemoSize', 255)
DBSetProp('RV_COMPANY_TYPE', 'View', 'FetchSize', 100)
DBSetProp('RV_COMPANY_TYPE', 'View', 'MaxRecords', -1)
DBSetProp('RV_COMPANY_TYPE', 'View', 'Tables', 'tbdata')
DBSetProp('RV_COMPANY_TYPE', 'View', 'Prepared', .F.)
DBSetProp('RV_COMPANY_TYPE', 'View', 'CompareMemo', .T.)
DBSetProp('RV_COMPANY_TYPE', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_COMPANY_TYPE', 'View', 'FetchSize', 100)
DBSetProp('RV_COMPANY_TYPE', 'View', 'Comment', "")
DBSetProp('RV_COMPANY_TYPE', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_COMPANY_TYPE', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_COMPANY_TYPE
* Props for the RV_COMPANY_TYPE.code field.
DBSetProp('RV_COMPANY_TYPE.code', 'Field', 'KeyField', .T.)
DBSetProp('RV_COMPANY_TYPE.code', 'Field', 'Updatable', .F.)
DBSetProp('RV_COMPANY_TYPE.code', 'Field', 'UpdateName', 'tbdata.code')
DBSetProp('RV_COMPANY_TYPE.code', 'Field', 'DataType', "C(2)")
* Props for the RV_COMPANY_TYPE.name field.
DBSetProp('RV_COMPANY_TYPE.name', 'Field', 'KeyField', .F.)
DBSetProp('RV_COMPANY_TYPE.name', 'Field', 'Updatable', .T.)
DBSetProp('RV_COMPANY_TYPE.name', 'Field', 'UpdateName', 'tbdata.name')
DBSetProp('RV_COMPANY_TYPE.name', 'Field', 'DataType', "C(50)")

***************** View setup for RV_TBCTRL ***************

CREATE SQL VIEW "RV_TBCTRL" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT * FROM tbctrl ORDER BY code

DBSetProp('RV_TBCTRL', 'View', 'UpdateType', 1)
DBSetProp('RV_TBCTRL', 'View', 'WhereType', 3)
DBSetProp('RV_TBCTRL', 'View', 'FetchMemo', .T.)
DBSetProp('RV_TBCTRL', 'View', 'SendUpdates', .F.)
DBSetProp('RV_TBCTRL', 'View', 'UseMemoSize', 255)
DBSetProp('RV_TBCTRL', 'View', 'FetchSize', 100)
DBSetProp('RV_TBCTRL', 'View', 'MaxRecords', -1)
DBSetProp('RV_TBCTRL', 'View', 'Tables', 'tbctrl')
DBSetProp('RV_TBCTRL', 'View', 'Prepared', .F.)
DBSetProp('RV_TBCTRL', 'View', 'CompareMemo', .T.)
DBSetProp('RV_TBCTRL', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_TBCTRL', 'View', 'FetchSize', 100)
DBSetProp('RV_TBCTRL', 'View', 'Comment', "")
DBSetProp('RV_TBCTRL', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_TBCTRL', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_TBCTRL
* Props for the RV_TBCTRL.code field.
DBSetProp('RV_TBCTRL.code', 'Field', 'KeyField', .T.)
DBSetProp('RV_TBCTRL.code', 'Field', 'Updatable', .F.)
DBSetProp('RV_TBCTRL.code', 'Field', 'UpdateName', 'tbctrl.code')
DBSetProp('RV_TBCTRL.code', 'Field', 'DataType', "C(2)")
* Props for the RV_TBCTRL.name field.
DBSetProp('RV_TBCTRL.name', 'Field', 'KeyField', .F.)
DBSetProp('RV_TBCTRL.name', 'Field', 'Updatable', .T.)
DBSetProp('RV_TBCTRL.name', 'Field', 'UpdateName', 'tbctrl.name')
DBSetProp('RV_TBCTRL.name', 'Field', 'DataType', "C(50)")

***************** View setup for RV_TBDATA ***************

CREATE SQL VIEW "RV_TBDATA" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT * FROM tbdata WHERE tabref = ?cTabref ORDER BY code

DBSetProp('RV_TBDATA', 'View', 'UpdateType', 1)
DBSetProp('RV_TBDATA', 'View', 'WhereType', 3)
DBSetProp('RV_TBDATA', 'View', 'FetchMemo', .T.)
DBSetProp('RV_TBDATA', 'View', 'SendUpdates', .T.)
DBSetProp('RV_TBDATA', 'View', 'UseMemoSize', 255)
DBSetProp('RV_TBDATA', 'View', 'FetchSize', 100)
DBSetProp('RV_TBDATA', 'View', 'MaxRecords', -1)
DBSetProp('RV_TBDATA', 'View', 'Tables', 'tbdata')
DBSetProp('RV_TBDATA', 'View', 'Prepared', .F.)
DBSetProp('RV_TBDATA', 'View', 'CompareMemo', .T.)
DBSetProp('RV_TBDATA', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_TBDATA', 'View', 'FetchSize', 100)
DBSetProp('RV_TBDATA', 'View', 'Comment', "")
DBSetProp('RV_TBDATA', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_TBDATA', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_TBDATA
* Props for the RV_TBDATA.tabref field.
DBSetProp('RV_TBDATA.tabref', 'Field', 'KeyField', .T.)
DBSetProp('RV_TBDATA.tabref', 'Field', 'Updatable', .T.)
DBSetProp('RV_TBDATA.tabref', 'Field', 'UpdateName', 'tbdata.tabref')
DBSetProp('RV_TBDATA.tabref', 'Field', 'DataType', "C(2)")
* Props for the RV_TBDATA.code field.
DBSetProp('RV_TBDATA.code', 'Field', 'KeyField', .T.)
DBSetProp('RV_TBDATA.code', 'Field', 'Updatable', .T.)
DBSetProp('RV_TBDATA.code', 'Field', 'UpdateName', 'tbdata.code')
DBSetProp('RV_TBDATA.code', 'Field', 'DataType', "C(2)")
* Props for the RV_TBDATA.name field.
DBSetProp('RV_TBDATA.name', 'Field', 'KeyField', .F.)
DBSetProp('RV_TBDATA.name', 'Field', 'Updatable', .T.)
DBSetProp('RV_TBDATA.name', 'Field', 'UpdateName', 'tbdata.name')
DBSetProp('RV_TBDATA.name', 'Field', 'DataType', "C(50)")

***************** View setup for RV_FRIEND02 ***************

CREATE SQL VIEW "RV_FRIEND02" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT lname, phone, bdate FROM friend WHERE sname BETWEEN ?cFmName AND ?cToName ORDER BY lname

DBSetProp('RV_FRIEND02', 'View', 'UpdateType', 1)
DBSetProp('RV_FRIEND02', 'View', 'WhereType', 3)
DBSetProp('RV_FRIEND02', 'View', 'FetchMemo', .T.)
DBSetProp('RV_FRIEND02', 'View', 'SendUpdates', .F.)
DBSetProp('RV_FRIEND02', 'View', 'UseMemoSize', 255)
DBSetProp('RV_FRIEND02', 'View', 'FetchSize', 100)
DBSetProp('RV_FRIEND02', 'View', 'MaxRecords', -1)
DBSetProp('RV_FRIEND02', 'View', 'Tables', 'friend')
DBSetProp('RV_FRIEND02', 'View', 'Prepared', .F.)
DBSetProp('RV_FRIEND02', 'View', 'CompareMemo', .T.)
DBSetProp('RV_FRIEND02', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_FRIEND02', 'View', 'FetchSize', 100)
DBSetProp('RV_FRIEND02', 'View', 'Comment', "")
DBSetProp('RV_FRIEND02', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_FRIEND02', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_FRIEND02
* Props for the RV_FRIEND02.lname field.
DBSetProp('RV_FRIEND02.lname', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND02.lname', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND02.lname', 'Field', 'UpdateName', 'friend.lname')
DBSetProp('RV_FRIEND02.lname', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND02.phone field.
DBSetProp('RV_FRIEND02.phone', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND02.phone', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND02.phone', 'Field', 'UpdateName', 'friend.phone')
DBSetProp('RV_FRIEND02.phone', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND02.bdate field.
DBSetProp('RV_FRIEND02.bdate', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND02.bdate', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND02.bdate', 'Field', 'UpdateName', 'friend.bdate')
********************************************************
*DBSetProp('RV_FRIEND02.bdate', 'Field', 'DataType', "T")
DBSetProp('RV_FRIEND02.bdate', 'Field', 'DataType', "D")
********************************************************

***************** View setup for RV_FRIEND01 ***************

CREATE SQL VIEW "RV_FRIEND01" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT 0 AS Selected, bdate, lname, phone, email, CONVERT(CHAR(10),bdate,101) AS idate  FROM friend  WHERE CONVERT(CHAR(10),bdate,101) BETWEEN ?cFmDate AND ?cToDate  ORDER BY lname

DBSetProp('RV_FRIEND01', 'View', 'UpdateType', 1)
DBSetProp('RV_FRIEND01', 'View', 'WhereType', 3)
DBSetProp('RV_FRIEND01', 'View', 'FetchMemo', .T.)
DBSetProp('RV_FRIEND01', 'View', 'SendUpdates', .F.)
DBSetProp('RV_FRIEND01', 'View', 'UseMemoSize', 255)
DBSetProp('RV_FRIEND01', 'View', 'FetchSize', 100)
DBSetProp('RV_FRIEND01', 'View', 'MaxRecords', -1)
DBSetProp('RV_FRIEND01', 'View', 'Tables', 'friend')
DBSetProp('RV_FRIEND01', 'View', 'Prepared', .F.)
DBSetProp('RV_FRIEND01', 'View', 'CompareMemo', .T.)
DBSetProp('RV_FRIEND01', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_FRIEND01', 'View', 'FetchSize', 100)
DBSetProp('RV_FRIEND01', 'View', 'Comment', "")
DBSetProp('RV_FRIEND01', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_FRIEND01', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_FRIEND01
* Props for the RV_FRIEND01.selected field.
DBSetProp('RV_FRIEND01.selected', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND01.selected', 'Field', 'Updatable', .F.)
DBSetProp('RV_FRIEND01.selected', 'Field', 'UpdateName', 'Selected')
DBSetProp('RV_FRIEND01.selected', 'Field', 'DataType', "I")
* Props for the RV_FRIEND01.bdate field.
DBSetProp('RV_FRIEND01.bdate', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND01.bdate', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND01.bdate', 'Field', 'UpdateName', 'friend.bdate')
**********************************************************
* DBSetProp('RV_FRIEND01.bdate', 'Field', 'DataType', "T")
DBSetProp('RV_FRIEND01.bdate', 'Field', 'DataType', "D")
**********************************************************
* Props for the RV_FRIEND01.lname field.
DBSetProp('RV_FRIEND01.lname', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND01.lname', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND01.lname', 'Field', 'UpdateName', 'friend.lname')
DBSetProp('RV_FRIEND01.lname', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND01.phone field.
DBSetProp('RV_FRIEND01.phone', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND01.phone', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND01.phone', 'Field', 'UpdateName', 'friend.phone')
DBSetProp('RV_FRIEND01.phone', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND01.email field.
DBSetProp('RV_FRIEND01.email', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND01.email', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND01.email', 'Field', 'UpdateName', 'friend.email')
DBSetProp('RV_FRIEND01.email', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND01.idate field.
DBSetProp('RV_FRIEND01.idate', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND01.idate', 'Field', 'Updatable', .F.)
DBSetProp('RV_FRIEND01.idate', 'Field', 'UpdateName', 'idate')
DBSetProp('RV_FRIEND01.idate', 'Field', 'DataType', "C(10)")

***************** View setup for RV_FRIEND ***************

CREATE SQL VIEW "RV_FRIEND" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT * FROM friend ORDER BY sname

DBSetProp('RV_FRIEND', 'View', 'UpdateType', 1)
DBSetProp('RV_FRIEND', 'View', 'WhereType', 3)
DBSetProp('RV_FRIEND', 'View', 'FetchMemo', .T.)
DBSetProp('RV_FRIEND', 'View', 'SendUpdates', .T.)
DBSetProp('RV_FRIEND', 'View', 'UseMemoSize', 255)
DBSetProp('RV_FRIEND', 'View', 'FetchSize', 100)
DBSetProp('RV_FRIEND', 'View', 'MaxRecords', -1)
DBSetProp('RV_FRIEND', 'View', 'Tables', 'friend')
DBSetProp('RV_FRIEND', 'View', 'Prepared', .F.)
DBSetProp('RV_FRIEND', 'View', 'CompareMemo', .T.)
DBSetProp('RV_FRIEND', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_FRIEND', 'View', 'FetchSize', 100)
DBSetProp('RV_FRIEND', 'View', 'Comment', "")
DBSetProp('RV_FRIEND', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_FRIEND', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_FRIEND
* Props for the RV_FRIEND.sname field.
DBSetProp('RV_FRIEND.sname', 'Field', 'KeyField', .T.)
DBSetProp('RV_FRIEND.sname', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.sname', 'Field', 'UpdateName', 'friend.sname')
DBSetProp('RV_FRIEND.sname', 'Field', 'DataType', "C(10)")
* Props for the RV_FRIEND.lname field.
DBSetProp('RV_FRIEND.lname', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.lname', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.lname', 'Field', 'UpdateName', 'friend.lname')
DBSetProp('RV_FRIEND.lname', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND.city field.
DBSetProp('RV_FRIEND.city', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.city', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.city', 'Field', 'UpdateName', 'friend.city')
DBSetProp('RV_FRIEND.city', 'Field', 'DataType', "C(2)")
* Props for the RV_FRIEND.bdate field.
DBSetProp('RV_FRIEND.bdate', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.bdate', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.bdate', 'Field', 'UpdateName', 'friend.bdate')
********************************************************
* DBSetProp('RV_FRIEND.bdate', 'Field', 'DataType', "T")
DBSetProp('RV_FRIEND.bdate', 'Field', 'DataType', "D")
********************************************************
* Props for the RV_FRIEND.phone field.
DBSetProp('RV_FRIEND.phone', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.phone', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.phone', 'Field', 'UpdateName', 'friend.phone')
DBSetProp('RV_FRIEND.phone', 'Field', 'DataType', "C(50)")
* Props for the RV_FRIEND.occupy field.
DBSetProp('RV_FRIEND.occupy', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.occupy', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.occupy', 'Field', 'UpdateName', 'friend.occupy')
DBSetProp('RV_FRIEND.occupy', 'Field', 'DataType', "C(2)")
* Props for the RV_FRIEND.company field.
DBSetProp('RV_FRIEND.company', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.company', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.company', 'Field', 'UpdateName', 'friend.company')
DBSetProp('RV_FRIEND.company', 'Field', 'DataType', "C(10)")
* Props for the RV_FRIEND.email field.
DBSetProp('RV_FRIEND.email', 'Field', 'KeyField', .F.)
DBSetProp('RV_FRIEND.email', 'Field', 'Updatable', .T.)
DBSetProp('RV_FRIEND.email', 'Field', 'UpdateName', 'friend.email')
DBSetProp('RV_FRIEND.email', 'Field', 'DataType', "C(50)")

***************** View setup for RV_COMPANY ***************

CREATE SQL VIEW "RV_COMPANY" ; 
   REMOTE CONNECT "rm_data" ; 
   AS SELECT * FROM company ORDER BY sname

DBSetProp('RV_COMPANY', 'View', 'UpdateType', 1)
DBSetProp('RV_COMPANY', 'View', 'WhereType', 3)
DBSetProp('RV_COMPANY', 'View', 'FetchMemo', .T.)
DBSetProp('RV_COMPANY', 'View', 'SendUpdates', .T.)
DBSetProp('RV_COMPANY', 'View', 'UseMemoSize', 255)
DBSetProp('RV_COMPANY', 'View', 'FetchSize', 100)
DBSetProp('RV_COMPANY', 'View', 'MaxRecords', -1)
DBSetProp('RV_COMPANY', 'View', 'Tables', 'company')
DBSetProp('RV_COMPANY', 'View', 'Prepared', .F.)
DBSetProp('RV_COMPANY', 'View', 'CompareMemo', .T.)
DBSetProp('RV_COMPANY', 'View', 'FetchAsNeeded', .F.)
DBSetProp('RV_COMPANY', 'View', 'FetchSize', 100)
DBSetProp('RV_COMPANY', 'View', 'Comment', "")
DBSetProp('RV_COMPANY', 'View', 'BatchUpdateCount', 1)
DBSetProp('RV_COMPANY', 'View', 'ShareConnection', .F.)

*!* Field Level Properties for RV_COMPANY
* Props for the RV_COMPANY.sname field.
DBSetProp('RV_COMPANY.sname', 'Field', 'KeyField', .T.)
DBSetProp('RV_COMPANY.sname', 'Field', 'Updatable', .T.)
DBSetProp('RV_COMPANY.sname', 'Field', 'UpdateName', 'company.sname')
DBSetProp('RV_COMPANY.sname', 'Field', 'DataType', "C(10)")
* Props for the RV_COMPANY.lname field.
DBSetProp('RV_COMPANY.lname', 'Field', 'KeyField', .F.)
DBSetProp('RV_COMPANY.lname', 'Field', 'Updatable', .T.)
DBSetProp('RV_COMPANY.lname', 'Field', 'UpdateName', 'company.lname')
DBSetProp('RV_COMPANY.lname', 'Field', 'DataType', "C(50)")
* Props for the RV_COMPANY.addr1 field.
DBSetProp('RV_COMPANY.addr1', 'Field', 'KeyField', .F.)
DBSetProp('RV_COMPANY.addr1', 'Field', 'Updatable', .T.)
DBSetProp('RV_COMPANY.addr1', 'Field', 'UpdateName', 'company.addr1')
DBSetProp('RV_COMPANY.addr1', 'Field', 'DataType', "C(50)")
* Props for the RV_COMPANY.addr2 field.
DBSetProp('RV_COMPANY.addr2', 'Field', 'KeyField', .F.)
DBSetProp('RV_COMPANY.addr2', 'Field', 'Updatable', .T.)
DBSetProp('RV_COMPANY.addr2', 'Field', 'UpdateName', 'company.addr2')
DBSetProp('RV_COMPANY.addr2', 'Field', 'DataType', "C(50)")
* Props for the RV_COMPANY.type field.
DBSetProp('RV_COMPANY.type', 'Field', 'KeyField', .F.)
DBSetProp('RV_COMPANY.type', 'Field', 'Updatable', .T.)
DBSetProp('RV_COMPANY.type', 'Field', 'UpdateName', 'company.type')
DBSetProp('RV_COMPANY.type', 'Field', 'DataType', "C(2)")


***** Table setup for USRPWD (free table) *****
CREATE TABLE 'DATA\USRPWD.DBF' FREE ( ;
 SNAME C(10) NOT NULL, ;
 PWD C(10) NOT NULL, ;
 LEVEL N(1,0) NOT NULL ;
)

***** Create index for USRPWD *****
IF NOT USED('USRPWD')
 USE USRPWD
ENDIF
SELECT USRPWD
INDEX ON sname TAG pkey FOR !DELETED() CANDIDATE ADDITIVE


****************************
* Initialized LOCAL tables *
****************************

* Rpttab.DBF
INSERT INTO rpttab (code,name) VALUES ('ab01','รายชื่อเพื่อนตามชื่อ')
INSERT INTO rpttab (code,name) VALUES ('ab02','รายชื่อเพื่อนตามจังหวัด')
INSERT INTO rpttab (code,name) VALUES ('ab03','รายชื่อเพื่อนตามอาชีพ')
INSERT INTO rpttab (code,name) VALUES ('ab04','ประเภทธุรกิจที่เพื่อนทำงานอยู่')

* Usrpwd.DBF
INSERT INTO usrpwd (sname,level) VALUES ('ABOOK',9)

CLOSE TABLE ALL
CLOSE DATABASE ALL


RETURN


*******************************************
* SPECIALIZED SETUP DATABASE TO EACH DBMS *
*******************************************
IF DBUSED('data')
	SET DATABASE TO data
ELSE
	OPEN DATABASE data
ENDIF

IF INDBC('rv_friend01','View')
  DELETE VIEW rv_friend01
ENDIF

* Remote view: MS SQL, SQL Anywhere
CREATE SQL VIEW rv_friend01 ;
  CONNECTION rm_data ;
	AS SELECT 0 AS selected, bdate, lname, phone, email, CONVERT(CHAR(10),bdate,101) AS idate ;
     FROM friend ;
     WHERE CONVERT(CHAR(10),bdate,101) BETWEEN ?cFmDate AND ?cToDate ;
     ORDER BY lname

* Remote view: Oracle
CREATE SQL VIEW rv_friend01 ;
  CONNECTION rm_data ;
 	AS SELECT 0 AS selected, bdate, lname, phone, email, TO_CHAR(bdate,'MM/DD') AS idate
     FROM friend ;
     WHERE TO_CHAR(bdate,'MM/DD') BETWEEN ?cFmDate AND ?cToDate ;
     ORDER BY lname

*****************************************
